# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdraw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='shape',
            new_name='geojson',
        ),
    ]
