# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdraw', '0002_auto_20170616_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='geojson',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
