# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 01:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdraw', '0003_auto_20170617_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('times_annotated', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
